index:
  path:  /
  defaults: { _controller: AppBundle:Static:index }
metier_list:
  path:  /keyword.{_format}
  defaults: { _controller: AppBundle:Keyword:list }
city_list:
  path:  /cities.{_format}
  defaults: { _controller: AppBundle:City:list }