racine:
  path:  /
  defaults: { _controller: AppBundle:Static:index }

index:
  path:  /index.html
  defaults: { _controller: AppBundle:Static:index }

keyword_list:
  path:  /keyword.{_format}
  defaults: { _controller: AppBundle:Keyword:list }

city_list:
  path:  /cidades.{_format}
  defaults: { _controller: AppBundle:City:list }

company_detail:
  path:  /detail-{name}-{id}.{_format}
  defaults: { _controller: AppBundle:Company:detail }
  options:
    expose: true

company_list:
  path:  /{keyword}-{city}-{postal_code}.{_format}
  defaults: { _controller: AppBundle:Company:list }
  options:
    expose: true

metier_list:
  path:  /profissoes.{_format}
  defaults: { _controller: AppBundle:Metier:list }
  options:
    expose: true    
